### ISSUE TITLE
'ping' errors

### ISSUE THREAD

**Issue by zzhangb4** [TheYoBots/Lishogi-Bot#1]
Bot is connected to lishogi.org:

With -v flag I get:

2021-01-10 12:18:18,122: Starting new HTTPS connection (1): lishogi.org:443
2021-01-10 12:18:18,678: https://lishogi.org:443 "GET /api/account HTTP/1.1" 200 808
2021-01-10 12:18:18,680: Welcome BlazikenBot2000!
2021-01-10 12:18:18,681: You're now connected to https://lishogi.org/ and awaiting challenges.
2021-01-10 12:18:20,972: ||| control_queue event: connected
2021-01-10 12:18:31,741: ||| control_queue event: ping
2021-01-10 12:18:33,006: ||| control_queue event: ping

When making a challenge against the ai player I get:

line0 = b'{"id":"WwtCt1WX","variant":{"key":"standard","name":"Standard","short":"Std"},"clock":{"initial":300000,"increment":0,"byoyomi":8000,"periods":1},"speed":"rapid","perf":{"name":"Rapid"},"rated":false,"createdAt":1610299229238,"white":{"id":"blazikenbot2000","name":"BlazikenBot2000","title":"BOT","rating":1500,"provisional":true},"black":{"aiLevel":1},"initialFen":"startpos","type":"gameFull","state":{"type":"gameState","moves":"","wtime":300000,"btime":300000,"winc":0,"binc":0,"wdraw":false,"bdraw":false,"status":"started"}}'

followed by the ||| control_queue event: ping

Thus bot is connected however doesn't play any moves. Perhaps I'll mess around some more and see what I come up with.

**Comment by TheYoBots** [comment]
For this issue I think there might be two solutions.

Firstly, I had made this commit earlier https://github.com/TheYoBots/Lishogi-Bot/commit/d8199ddf2a8eeea089e21e62ea457e2e3c07496c but wasn’t to sure of it and assume that I’ll have to reverse it and use USI itself instead of USI.

Another thing is that you can edit the .yml files that uses shogi instead of just editing the config.yml.default file. I feel apreey.yml should work the best https://github.com/TheYoBots/Lishogi-Bot/blob/master/apery.yml or fairy.yml https://github.com/TheYoBots/Lishogi-Bot/blob/master/fairy.yml

**Comment by zzhangb4** [comment]
Most recent logs:
2021-01-10 18:06:05,671: Starting new HTTPS connection (1): lishogi.org:443
2021-01-10 18:06:06,229: https://lishogi.org:443 "GET /api/account HTTP/1.1" 200 916
2021-01-10 18:06:06,231: Welcome BlazikenBot2000!
2021-01-10 18:06:06,232: You're now connected to https://lishogi.org/ and awaiting challenges.
2021-01-10 18:06:09,235: Something went wrong. Game is starting and we don't have a queued process
2021-01-10 18:06:09,236: --- Process Used. Total Queued: 0. Total Used: 1

This reminds me of lichess-bot errors, something about engine not communicating with lichess-bot, or not at all (!).

**Comment by TheYoBots** [comment]
Guess my edit in engine.py (https://github.com/TheYoBots/Lishogi-Bot/commit/c7a8bece00bb1a8139e88ff2d77d4291a2e50971) would have resulted in this. I’ve reverse the changes (https://github.com/TheYoBots/Lishogi-Bot/commit/5feb1b5fa91e0e3c40bcecbc89689f6301317d6b), I don’t think it will happen again.

**Comment by TheYoBots** [comment]
@zzhangb4 I have managed to resolve the ‘ping’ error. I am receiving the logs, `control_queue event: connected`. After which I don’t receive any ‘ping’ logs. But other than that I am recieving these logs on and on

https://user-images.githubusercontent.com/73843275/104360344-e7c56380-5536-11eb-9493-f0b2cba7d568.mov

Sorry I had minimised the window during the recording.

**Comment by zzhangb4** [comment]
The "Not Found for url: ../api/seek" problem can be solved (ignored?) by just removing the create-challenge part altogether: https://github.com/TheYoBots/Lishogi-Bot/blob/6ef8fdece00b08bfe38b892cd73847889198b4e9/lishogi-bot.py#L114 (look at line 117). That way the bot won't randomly create challenges by itself.

**Comment by TheYoBots** [comment]
I don’t think that would work as the variant (in this case shogi) will not be identified if it is removed.

**Comment by TheYoBots** [comment]
Now that it’s working and the error doesn’t seem to happen, I’ll close this Issue.

Thanks for your help!!
