### ISSUE TITLE
./.venv/Scripts/Activate.ps1 Command not working

### ISSUE THREAD

**Issue by TheLibots** [TheYoBots/Lishogi-Bot#16]
Microsoft Windows [Version 10.0.19042.867]
(c) 2020 Microsoft Corporation. All rights reserved.

C:\Users\Web Development>python -m pip install --upgrade pip
Requirement already satisfied: pip in c:\users\web development\appdata\local\programs\python\python39\lib\site-packages (21.1.2)

C:\Users\Web Development>cd C:\Users\Web Development\Downloads\Lishogi-Bot-master\Lishogi-Bot-master

C:\Users\Web Development\Downloads\Lishogi-Bot-master\Lishogi-Bot-master>pip install virtualenv
Requirement already satisfied: virtualenv in c:\users\web development\appdata\local\programs\python\python39\lib\site-packages (20.4.6)
Requirement already satisfied: six<2,>=1.9.0 in c:\users\web development\appdata\local\programs\python\python39\lib\site-packages (from virtualenv) (1.16.0)
Requirement already satisfied: appdirs<2,>=1.4.3 in c:\users\web development\appdata\local\programs\python\python39\lib\site-packages (from virtualenv) (1.4.4)
Requirement already satisfied: filelock<4,>=3.0.0 in c:\users\web development\appdata\local\programs\python\python39\lib\site-packages (from virtualenv) (3.0.12)
Requirement already satisfied: distlib<1,>=0.3.1 in c:\users\web development\appdata\local\programs\python\python39\lib\site-packages (from virtualenv) (0.3.1)

C:\Users\Web Development\Downloads\Lishogi-Bot-master\Lishogi-Bot-master>python -m venv .venv

C:\Users\Web Development\Downloads\Lishogi-Bot-master\Lishogi-Bot-master>./.venv/Scripts/Activate.ps1
'.' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\Web Development\Downloads\Lishogi-Bot-master\Lishogi-Bot-master>

**Comment by TheYoBots** [comment]
As clearly said,
> `.\.venv\Scripts\activate.bat` should work in cmd in administator mode. This may not work on Windows, and in this case you need to execute "Set-ExecutionPolicy RemoteSigned" first and choose "Y" there (you may need to run Powershell as administrator). After you executed the script, change execution policy back with "Set-ExecutionPolicy Restricted" and pressing "Y").

So do use `.\.venv\Scripts\activate.bat` instead.
