### ISSUE TITLE
Bug in Urllib3 Update from 1.26.4 to 1.26.5

### ISSUE THREAD

**Issue by TheYoBots** [TheYoBots/Lishogi-Bot#23]
I faced a bug upgrading from urllib3 1.26.4 to 1.26.5 (https://github.com/TheYoBots/Lishogi-Bot/commit/a3895f0188d17f886a4bb82b503f521b8cc71233). If anyone else is facing any error with this update do mention it in this issue with:
- Your error logs.
- Your `requirements.txt` file (to see which version other dependencies are at).

If you don’t face any such issue do comment here mentioning it.

**Comment by MarkZH** [comment]
I haven't had any errors with the latest urllib3.

**Comment by TheYoBots** [comment]
Thanks, I too have stopped facing this error. I think I should close this now.
