### ISSUE TITLE
!name command error

### ISSUE THREAD

**Issue by littlebasiccoder** [TheYoBots/Lishogi-Bot#37]
The **!name** command only reply the lishogi bot version not the engine like **bot** **running** **on** **fairyStockfish** **Lishogi-Bot** **v1.0.0**

Thanks! for considering the issue

**Comment by TheYoBots** [comment]
What do you mean? Could you provide an example? Maybe you could give a game in which you faced this error and provide more details.

**Comment by littlebasiccoder** [comment]
**oh sorry it worked Thanks!**

**Comment by TheYoBots** [comment]
Lmao ok
